use std::collections::HashMap;
use std::fmt;
use std::time::{Duration, Instant};

// ─── Asteria Performance Profiler & Metrics ────────────────────────
//
// Microsecond-precision timing instrumentation for measuring each pipeline
// stage (ParseHtml, ParseCss, ResolveStyles, Layout, Paint, Render).
// Provides zero-allocation RAII scope guards and human-readable summary
// reports for devtools diagnostics and CLI inspection.

/// Core pipeline stages tracked by the profiler.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EngineStage {
    ParseHtml,
    ParseCss,
    ResolveStyles,
    Layout,
    Paint,
    SceneBuild,
    Render,
}

impl fmt::Display for EngineStage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EngineStage::ParseHtml => write!(f, "HTML Parsing"),
            EngineStage::ParseCss => write!(f, "CSS Parsing"),
            EngineStage::ResolveStyles => write!(f, "Style Resolution"),
            EngineStage::Layout => write!(f, "2D Layout Engine"),
            EngineStage::Paint => write!(f, "Display List Paint"),
            EngineStage::SceneBuild => write!(f, "Scene Graph Build"),
            EngineStage::Render => write!(f, "GPU Render Pass"),
        }
    }
}

/// Consolidated performance report for a complete engine pipeline run.
#[derive(Debug, Clone, Default)]
pub struct ProfileReport {
    /// Microsecond/millisecond duration spent in each engine stage
    pub stage_durations: HashMap<EngineStage, Duration>,
    /// Total wall-clock time from pipeline start to finish
    pub total_duration: Duration,
    /// Total DOM nodes created during HTML parsing
    pub dom_nodes_count: usize,
    /// Total LayoutBox nodes constructed by layout engine
    pub layout_boxes_count: usize,
    /// Total DisplayCommands generated by paint engine
    pub display_commands_count: usize,
}

impl ProfileReport {
    /// Calculate estimated frames per second (FPS) based on total pipeline duration.
    pub fn estimated_fps(&self) -> f64 {
        let secs = self.total_duration.as_secs_f64();
        if secs > 0.0 { 1.0 / secs } else { 0.0 }
    }

    /// Format a clean, human-readable terminal summary of the performance metrics.
    pub fn format_summary(&self) -> String {
        let mut out = String::new();
        out.push_str("── Asteria Engine Performance Profile ──────────────────\n");

        let total_ms = self.total_duration.as_secs_f64() * 1000.0;
        out.push_str(&format!(
            "Total Pipeline Duration : {:.3} ms ({:.1} FPS)\n",
            total_ms,
            self.estimated_fps()
        ));
        out.push_str(&format!(
            "DOM Nodes / Layout / Commands: {} / {} / {}\n",
            self.dom_nodes_count, self.layout_boxes_count, self.display_commands_count
        ));
        out.push_str("────────────────────────────────────────────────────────\n");

        let stages = [
            EngineStage::ParseHtml,
            EngineStage::ParseCss,
            EngineStage::ResolveStyles,
            EngineStage::Layout,
            EngineStage::Paint,
            EngineStage::SceneBuild,
            EngineStage::Render,
        ];

        for stage in stages {
            if let Some(dur) = self.stage_durations.get(&stage) {
                let ms = dur.as_secs_f64() * 1000.0;
                let pct = if total_ms > 0.0 {
                    (ms / total_ms) * 100.0
                } else {
                    0.0
                };
                out.push_str(&format!(
                    "  [+] {:<20} : {:8.3} ms ({:5.1}%)\n",
                    stage.to_string(),
                    ms,
                    pct
                ));
            }
        }

        out.push_str("────────────────────────────────────────────────────────\n");
        out
    }
}

/// RAII guard that automatically records stage duration when dropped.
#[must_use = "dropping the guard immediately will record a 0-duration timing measurement"]
pub struct StageGuard<'a> {
    stage: EngineStage,
    start_time: Instant,
    profiler: &'a mut EngineProfiler,
}

impl<'a> Drop for StageGuard<'a> {
    fn drop(&mut self) {
        let elapsed = self.start_time.elapsed();
        self.profiler.record_stage_duration(self.stage, elapsed);
    }
}

/// The core engine performance profiler.
#[derive(Debug, Default)]
pub struct EngineProfiler {
    durations: HashMap<EngineStage, Duration>,
    total_start: Option<Instant>,
    finalized_total_duration: Option<Duration>,
    dom_nodes_count: usize,
    layout_boxes_count: usize,
    display_commands_count: usize,
}

impl EngineProfiler {
    /// Create a new `EngineProfiler`.
    pub fn new() -> Self {
        EngineProfiler {
            durations: HashMap::new(),
            total_start: None,
            finalized_total_duration: None,
            dom_nodes_count: 0,
            layout_boxes_count: 0,
            display_commands_count: 0,
        }
    }

    /// Mark the start of a complete engine pipeline run.
    pub fn start_pipeline(&mut self) {
        self.durations.clear();
        self.dom_nodes_count = 0;
        self.layout_boxes_count = 0;
        self.display_commands_count = 0;
        self.finalized_total_duration = None;
        self.total_start = Some(Instant::now());
    }

    /// Record an explicit duration for a specific stage.
    pub fn record_stage_duration(&mut self, stage: EngineStage, duration: Duration) {
        *self.durations.entry(stage).or_insert(Duration::ZERO) += duration;
    }

    /// Time a code block via RAII scope guard.
    /// Duration is automatically recorded when the guard goes out of scope.
    pub fn time_stage(&mut self, stage: EngineStage) -> StageGuard<'_> {
        StageGuard {
            stage,
            start_time: Instant::now(),
            profiler: self,
        }
    }

    /// Update pipeline output node counts.
    pub fn set_counts(&mut self, dom_nodes: usize, layout_boxes: usize, display_commands: usize) {
        self.dom_nodes_count = dom_nodes;
        self.layout_boxes_count = layout_boxes;
        self.display_commands_count = display_commands;
    }

    /// Finish the pipeline measurement and generate a `ProfileReport`.
    pub fn finish_pipeline(&mut self) -> ProfileReport {
        let total_duration = match self.finalized_total_duration {
            Some(duration) => duration,
            None => {
                let start_elapsed = self
                    .total_start
                    .take()
                    .map(|start| start.elapsed())
                    .unwrap_or_default();
                let recorded_elapsed = self.durations.values().copied().sum::<Duration>();
                let duration = start_elapsed.max(recorded_elapsed);
                self.finalized_total_duration = Some(duration);
                duration
            }
        };

        ProfileReport {
            stage_durations: self.durations.clone(),
            total_duration,
            dom_nodes_count: self.dom_nodes_count,
            layout_boxes_count: self.layout_boxes_count,
            display_commands_count: self.display_commands_count,
        }
    }
}

// ─── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::thread::sleep;

    #[test]
    fn test_stage_guard_timing() {
        let mut profiler = EngineProfiler::new();
        profiler.start_pipeline();

        {
            let guard = profiler.time_stage(EngineStage::ParseHtml);
            sleep(Duration::from_millis(5));
            drop(guard);
        }

        {
            let guard = profiler.time_stage(EngineStage::Layout);
            sleep(Duration::from_millis(5));
            drop(guard);
        }

        profiler.set_counts(10, 5, 3);
        let report = profiler.finish_pipeline();

        assert!(report.stage_durations.contains_key(&EngineStage::ParseHtml));
        assert!(report.stage_durations.contains_key(&EngineStage::Layout));
        assert!(report.total_duration >= Duration::from_millis(10));
        assert_eq!(report.dom_nodes_count, 10);
        assert_eq!(report.layout_boxes_count, 5);
        assert_eq!(report.display_commands_count, 3);
    }

    #[test]
    fn test_format_summary() {
        let mut report = ProfileReport::default();
        report
            .stage_durations
            .insert(EngineStage::ParseHtml, Duration::from_millis(10));
        report
            .stage_durations
            .insert(EngineStage::Layout, Duration::from_millis(20));
        report.total_duration = Duration::from_millis(30);

        let summary = report.format_summary();
        assert!(summary.contains("Asteria Engine Performance Profile"));
        assert!(summary.contains("HTML Parsing"));
        assert!(summary.contains("2D Layout Engine"));
        assert!(summary.contains("30.000 ms"));
    }

    #[test]
    fn test_finish_pipeline_consumes_total_start() {
        let mut profiler = EngineProfiler::new();
        profiler.start_pipeline();
        profiler.record_stage_duration(EngineStage::ParseHtml, Duration::from_millis(15));

        let report1 = profiler.finish_pipeline();
        assert!(report1.total_duration >= Duration::from_millis(15));

        let report2 = profiler.finish_pipeline();
        assert_eq!(report2.total_duration, report1.total_duration);
    }
}
